name: heart_rate
description: "Heart Rate APP"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ## t2 -- Presentation
  flutter_svg: ^2.0.5
  auto_animated_list: ^1.0.4
  syncfusion_flutter_charts: ^27.1.52
  ## t2 -- Providers
  cloud_firestore: ^4.3.1
  firebase_database: ^10.2.0
  http: ^0.13.0
  ## t2 -- Services
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  logger: ^1.1.0
  min_id: ^1.1.0
  firebase_crashlytics: ^3.3.5
  form_controller: ^0.8.4
  google_fonts: ^4.0.4
  awesome_notifications: ^0.9.3+1
  geolocator: ^13.0.1
  ## t2 -- Firebase
  firebase: ^9.0.2
  firebase_auth: ^4.5.0
  firebase_storage: ^11.2.1
  permission_handler: ^11.3.1
  ## t2 -- Other Utilities
  flutter_blue_plus: ^1.33.4


##!SECTION --Development Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.1.8
  flutter_application_id: ^2.0.0-dev
  flutter_native_splash: ^2.2.17


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/